[package]
name = "hacker_rank"
version = "0.1.0"
authors = ["scotto3394 <shm.qed@gmail.com>"]

[lib]
name = "rust_bucket"
path = "src/lib.rs"

[[bin]]
name = "sandbox"
path = "src/main.rs"
[dependencies]
